GAME:{GAME}
{+PLAYERS}
{_PLAYERSTATE}READY,NOTREADY,SPECT{__PLAYERSTATE}
<div>
{PLAYER} {_PLAYERSTATEREADY}READY{__PLAYERSTATEREADY}{_PLAYERSTATENOTREADY}NOT READY{__PLAYERSTATENOTREADY}{_PLAYERSTATESPECT}SPECT{__PLAYERSTATESPECT}
</div>
{++PLAYERS}
<a href="?action=part">Part</a>
{_IMREADY}<a href="?action=notready">Notready</a>{__IMREADY}
{_IMNOTREADY}<a href="?action=ready">Ready</a>{__IMNOTREADY}

